name: Create folder on push

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use the checkout action to access the repo files
      
    - name: Run Trivy vulnerability scanner
      run: |
          OUTPUT_FILE="GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          mkdir -p "GitHub Actions/Trivy Automation"
          trivy image --format json --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" nginx:latest

    - name: Verify scan results exist
      run: ls -l "GitHub Actions/Trivy Automation/"

    - name: Commit scan results to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add "GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
        git commit -m "Add Trivy scan results (${DATE})"
        git push origin HEAD:main